// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire3wireusagewitherr

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeEvent(phrase string) (Event, error) {
	message := NewMessage(phrase)
	greater := NewGreater(message)
	event, err := NewEvent(greater)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}

// wire.go:

func AdditionalProvider() int {
	return 1
}

// superSet 对应的 wire.NewSet 不能和 wire.Build 一起使用
var superSet wire.ProviderSet = wire.NewSet(NewMessage, NewEvent, NewGreater)
