// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire7struct_field_provider

// Injectors from wire.go:

func injectPersonName() string {
	person := ProvidePerson()
	string2 := GetName(person)
	return string2
}

func InitializePersonAge() int {
	person := ProvidePerson()
	int2 := person.Age
	return int2
}
