// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire1easy

// Injectors from wire.go:

func InitializeEvent() Event {
	message := NewMessage()
	greater := NewGreater(message)
	event := NewEvent(greater)
	return event
}
