// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package greater3changeinjectsinnature

// Injectors from wire.go:

func InitializeEvent(phrase string) (Event, error) {
	message := NewMessage(phrase)
	greater := NewGreater(message)
	event, err := NewEvent(greater)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}
