// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package foobar

// Injectors from wire.go:

func InitializeBar() Bar {
	myFooer := ProvideMyFooer()
	bar := ProvideBar(myFooer)
	return bar
}
