// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bindvalue

// Injectors from wire.go:

func InitializeValueWrapper() ValueWrapper {
	valueWrapper := _wireValueWrapperValue
	return valueWrapper
}

var (
	_wireValueWrapperValue = ValueWrapper{Value: "value"}
)
